<?php
/**
 * Created by adam
 * Date: 09.12.13
 */

require_once( dirname( __FILE__ ) . '/../Maintenance.php' );

class TvEpisodesCovarage extends Maintenance {

	public function execute() {
//		$this->call( 'muppet', 'kermit' );
		foreach( $this->seriesList as $series => $episode ) {
			$data = $this->call( $series, $episode );
			if ( is_array( $data ) ) {
				var_dump( $data[ 'url' ] );
			} else {
				var_dump( $data );
			}
		}
	}

	protected function call( $seriesName, $episodeName ) {
		var_dump( 1 );
		try {
		$result = F::app()->sendRequest( 'TvApi', 'getEpisode',
			[ 'seriesName' => $seriesName, 'episodeName' => $episodeName ], true );
		} catch( Exception $e ) {
			return $e->getCode();
		}
		return $result->getData();
	}

	protected $seriesList = [ '1600 Penn' => 'Pilot',
		'2 Broke Girls' => 'Pilot',
		'30 Rock' => 'Pilot',
		'90210' => 'Pilot',
		'A Touch of Cloth' => 'Pilot',
		'A Young Doctor\'s Notebook' => 'Pilot',
		'Almost Human' => 'Pilot',
		'Alpha House' => 'Pilot',
		'American Dad' => 'Pilot',
		'American Horror Story' => 'Pilot',
		'American Horror Story : Asylum' => 'Pilot',
		'American Idol' => 'Pilot',
		'Americas Next Top Model' => 'Pilot',
		'Anger Management' => 'Pilot',
		'Anger Managment' => 'Pilot',
		'Archer' => 'Pilot',
		'Army' => 'Pilot',
		'Army Wives' => 'Pilot',
		'Arrested Development' => 'Pilot',
		'Arrow' => 'Pilot',
		'Artic Air' => 'Pilot',
		'Atlantis' => 'Pilot',
		'Avengers Assemble' => 'Pilot',
		'Awkward' => 'Pilot',
		'Baby Daddy' => 'Pilot',
		'Back In The Game' => 'Pilot',
		'Bad Education' => 'Pilot',
		'Banshee' => 'Pilot',
		'Bates Motel' => 'Pilot',
		'Beauty And The Beast' => 'Pilot',
		'Being Human UK' => 'Pilot',
		'Being Human US' => 'Pilot',
		'Ben and Kate' => 'Pilot',
		'Betas' => 'Pilot',
		'Betrayal' => 'Pilot',
		'Beware the Batman' => 'Pilot',
		'Big School' => 'Pilot',
		'Blue Bloods' => 'Pilot',
		'Boardwalk Empire' => 'Pilot',
		'Bob\'s Burger' => 'Pilot',
		'Body Of Proof' => 'Pilot',
		'Bomb Girls' => 'Pilot',
		'Bones' => 'Pilot',
		'Breaking Bad' => 'Pilot',
		'Bron/Broen' => 'Pilot',
		'Brooklyn Nine-Nine' => 'Pilot',
		'Bunhead' => 'Pilot',
		'Bunheads' => 'Pilot',
		'Burn Notice' => 'Pilot',
		'By Any Means' => 'Pilot',
		'Californication' => 'Pilot',
		'Call Me Fitz' => 'Pilot',
		'Camp' => 'Pilot',
		'Castle' => 'Pilot',
		'Cedar Cove' => 'Pilot',
		'Chicago Fire' => 'Pilot',
		'Chickens' => 'Pilot',
		'Childrens Hospital' => 'Pilot',
		'Comic Book Men' => 'Pilot',
		'Community' => 'Pilot',
		'Continuum' => 'Pilot',
		'Copper' => 'Pilot',
		'Cougar Town' => 'Pilot',
		'Covert Affairs' => 'Pilot',
		'Cracked' => 'Pilot',
		'Criminal Minds' => 'Pilot',
		'Crossing Lines' => 'Pilot',
		'CSI' => 'Pilot',
		'CSI : NY' => 'Pilot',
		'Cult' => 'Pilot',
		'Da Vinci\'s Demons' => 'Pilot',
		'Dads' => 'Pilot',
		'Dallas' => 'Pilot',
		'Damages' => 'Pilot',
		'Dancing With the Stars' => 'Pilot',
		'Deception' => 'Pilot',
		'Defiance' => 'Pilot',
		'Devious Maids' => 'Pilot',
		'Dexter' => 'Pilot',
		'Do No Harm' => 'Pilot',
		'Doctor Who' => 'Pilot',
		'Doctor Who : Doctors Revisited' => 'Pilot',
		'Doctor Who : The Doctors Revisited' => 'Pilot',
		'Don\'t Trust The Bitch In Apartment 23' => 'Pilot',
		'Downton Abbey' => 'Pilot',
		'Dracula' => 'Pilot',
		'Drop Dead Diva' => 'Pilot',
		'Eastbound and Down' => 'Pilot',
		'Elementary' => 'Pilot',
		'Emily Owens, M.D.' => 'Pilot',
		'Enlightened' => 'Pilot',
		'Entourage' => 'Pilot',
		'Eureka' => 'Pilot',
		'Falling Skies' => 'Pilot',
		'Family Guy' => 'Pilot',
		'Family Tools' => 'Pilot',
		'Family Tree' => 'Pilot',
		'Franklin And Bash' => 'Pilot',
		'Fringe' => 'Pilot',
		'Futurama' => 'Pilot',
		'Futurama7' => 'Pilot',
		'Game Of Thrones' => 'Pilot',
		'Getting On' => 'Pilot',
		'Girls' => 'Pilot',
		'Glee' => 'Pilot',
		'Go On' => 'Pilot',
		'Golden Boy' => 'Pilot',
		'Golden Globe Awards' => 'Pilot',
		'Graceland' => 'Pilot',
		'Grey\'s Anatomy' => 'Pilot',
		'Greys Anatomy' => 'Pilot',
		'Grimm' => 'Pilot',
		'Ground Floor' => 'Pilot',
		'Guys With Kids' => 'Pilot',
		'Hannibal' => 'Pilot',
		'Happily Divorced' => 'Pilot',
		'Happily Divrorced' => 'Pilot',
		'Happy Endings' => 'Pilot',
		'Hart Of Dixie' => 'Pilot',
		'Haven' => 'Pilot',
		'Hawaii Five-0' => 'Pilot',
		'Hawaii Five-O' => 'Pilot',
		'Heartland' => 'Pilot',
		'Hell on Wheels' => 'Pilot',
		'Hell\'s Kitchen' => 'Pilot',
		'Hello Ladies' => 'Pilot',
		'Hemlock Grove' => 'Pilot',
		'History Detectives' => 'Pilot',
		'Hit The Floor' => 'Pilot',
		'Homeland' => 'Pilot',
		'Hostages' => 'Pilot',
		'Hot In Cleveland' => 'Pilot',
		'House of Cards' => 'Pilot',
		'House Of Lies' => 'Pilot',
		'How I Met Your Mother' => 'Pilot',
		'How To Live With Your Parents' => 'Pilot',
		'How To Live With Your Parents For The Rest Of Your' => 'Pilot',
		'Hulk And The Agents of S.M.A.S.H' => 'Pilot',
		'Hulk And The Agents of S.M.A.S.H.' => 'Pilot',
		'Ironside' => 'Pilot',
		'It\'s Always Sunny in Philadelphia' => 'Pilot',
		'Justified' => 'Pilot',
		'King and Maxwell' => 'Pilot',
		'Kitchen Nightmares' => 'Pilot',
		'Last Man Standing' => 'Pilot',
		'Last Resort' => 'Pilot',
		'Law & Order : SVU' => 'Pilot',
		'Law and Order SVU' => 'Pilot',
		'Legit' => 'Pilot',
		'Lilyhammer' => 'Pilot',
		'Longmire' => 'Pilot',
		'Lost Girl' => 'Pilot',
		'Low Winter Sun' => 'Pilot',
		'Lucky 7' => 'Pilot',
		'Luther' => 'Pilot',
		'Mad Dogs' => 'Pilot',
		'Mad Men' => 'Pilot',
		'Magic City' => 'Pilot',
		'Major Crimes' => 'Pilot',
		'Malibu Country' => 'Pilot',
		'Maron' => 'Pilot',
		'Marvel\'s Agents of S.H.I.E.L.D.' => 'Pilot',
		'Masters of Sex' => 'Pilot',
		'Melissa and Joey' => 'Pilot',
		'Men At Work' => 'Pilot',
		'Mike and Molly' => 'Pilot',
		'Misfits' => 'Pilot',
		'Mistresses' => 'Pilot',
		'Mob City' => 'Pilot',
		'Modern Family' => 'Pilot',
		'Mom' => 'Pilot',
		'Monday Mornings' => 'Pilot',
		'Motive' => 'Pilot',
		'Murdoch Mysteries' => 'Pilot',
		'Nashville' => 'Pilot',
		'NCIS' => 'Pilot',
		'NCIS : LA' => 'Pilot',
		'NCIS LA' => 'Pilot',
		'Necessary Roughness' => 'Pilot',
		'New Girl' => 'Pilot',
		'Nikita' => 'Pilot',
		'Nurse Jackie' => 'Pilot',
		'Once Upon A Time' => 'Pilot',
		'Once Upon A Time In Wonderland' => 'Pilot',
		'Orange Is The New Black' => 'Pilot',
		'Orphan Black' => 'Pilot',
		'Parenthood' => 'Pilot',
		'Parks And Recreation' => 'Pilot',
		'Peaky Blinders' => 'Pilot',
		'Perception' => 'Pilot',
		'Person Of Interest' => 'Pilot',
		'Played' => 'Pilot',
		'Portlandia' => 'Pilot',
		'Pretty Little Liars' => 'Pilot',
		'Private Practice' => 'Pilot',
		'Project Runway' => 'Pilot',
		'Psych' => 'Pilot',
		'Raising Hope' => 'Pilot',
		'Ravenswood' => 'Pilot',
		'Ray Donovan' => 'Pilot',
		'Rectify' => 'Pilot',
		'Red Widow' => 'Pilot',
		'Reign' => 'Pilot',
		'Republic of Doyle' => 'Pilot',
		'Revenge' => 'Pilot',
		'Revolution' => 'Pilot',
		'Ripper Street' => 'Pilot',
		'Rizzoli and Isles' => 'Pilot',
		'Robot Chicken' => 'Pilot',
		'Rogue' => 'Pilot',
		'Rookie Blue' => 'Pilot',
		'Royal Pains' => 'Pilot',
		'Rules Of Engagment' => 'Pilot',
		'SAF3' => 'Pilot',
		'Saturday Night Live' => 'Pilot',
		'Save Me' => 'Pilot',
		'Saving Hope' => 'Pilot',
		'Scandal' => 'Pilot',
		'ScienceNow' => 'Pilot',
		'Sean Saves The World' => 'Pilot',
		'Seed' => 'Pilot',
		'Shameless' => 'Pilot',
		'Siberia' => 'Pilot',
		'Skins (UK)' => 'Pilot',
		'Sleepy Hollow' => 'Pilot',
		'Smash' => 'Pilot',
		'Sons Of Anarchy' => 'Pilot',
		'South Park' => 'Pilot',
		'Southland' => 'Pilot',
		'Spartacus : War Of The Damned' => 'Pilot',
		'Strike Back' => 'Pilot',
		'Suburgatory' => 'Pilot',
		'Suits' => 'Pilot',
		'Sullivan and Son' => 'Pilot',
		'Super Fun Night' => 'Pilot',
		'Supernatural' => 'Pilot',
		'Survivor' => 'Pilot',
		'Switched At Birth' => 'Pilot',
		'Talking Dead' => 'Pilot',
		'Teen Wolf' => 'Pilot',
		'The Amazing Race' => 'Pilot',
		'The Americans' => 'Pilot',
		'The Apprentice' => 'Pilot',
		'The Big Bang Theory' => 'Pilot',
		'The Big C' => 'Pilot',
		'The Birthday Boys' => 'Pilot',
		'The Blacklist' => 'Pilot',
		'The Borgias' => 'Pilot',
		'The Bridge' => 'Pilot',
		'The Carrie Diaries' => 'Pilot',
		'The Cleveland Show' => 'Pilot',
		'The Client List' => 'Pilot',
		'The Crazy Ones' => 'Pilot',
		'The Exes' => 'Pilot',
		'The Fall' => 'Pilot',
		'The Following' => 'Pilot',
		'The Fosters' => 'Pilot',
		'The Glades' => 'Pilot',
		'The Goldbergs' => 'Pilot',
		'The Good Wife' => 'Pilot',
		'The Goodwin Games' => 'Pilot',
		'The Job Lot' => 'Pilot',
		'The Killing' => 'Pilot',
		'The League' => 'Pilot',
		'The Legend of Korra' => 'Pilot',
		'The Listener' => 'Pilot',
		'The Lying Game' => 'Pilot',
		'The Mentalist' => 'Pilot',
		'The Michael J. Fox Show' => 'Pilot',
		'The Middle' => 'Pilot',
		'The Millers' => 'Pilot',
		'The Mindy Project' => 'Pilot',
		'The Mob Doctor' => 'Pilot',
		'The Neighbors' => 'Pilot',
		'The Nerdist' => 'Pilot',
		'The New Normal' => 'Pilot',
		'The Newsroom' => 'Pilot',
		'The Office' => 'Pilot',
		'The Originals' => 'Pilot',
		'The Secret Life Of The American Teenager' => 'Pilot',
		'The Simpsons' => 'Pilot',
		'The Soul Man' => 'Pilot',
		'The Tomorrow People' => 'Pilot',
		'The Tunnel' => 'Pilot',
		'The Universe' => 'Pilot',
		'The Vampire Diaries' => 'Pilot',
		'The Venture Brothers' => 'Pilot',
		'The Village' => 'Pilot',
		'The Voice' => 'Pilot',
		'The Walking Dead' => 'Pilot',
		'The White Queen' => 'Pilot',
		'The X Factor' => 'Pilot',
		'Tne Simpsons' => 'Pilot',
		'Top Of The Lake' => 'Pilot',
		'Touch' => 'Pilot',
		'Treme' => 'Pilot',
		'Trophy Wife' => 'Pilot',
		'True Blood' => 'Pilot',
		'Twisted' => 'Pilot',
		'Two and A Half Men' => 'Pilot',
		'Under The Dome' => 'Pilot',
		'Unforgettable' => 'Pilot',
		'United States Of Tara' => 'Pilot',
		'Veep' => 'Pilot',
		'Vegas' => 'Pilot',
		'Vicious' => 'Pilot',
		'Vikings' => 'Pilot',
		'Warehouse 13' => 'Pilot',
		'We Are Men' => 'Pilot',
		'Web Therapy' => 'Pilot',
		'Welcome To The Family' => 'Pilot',
		'White Collar' => 'Pilot',
		'Whitechapel' => 'Pilot',
		'Whitney' => 'Pilot',
		'Wilfred' => 'Pilot',
		'Witches of East End' => 'Pilot',
		'Zach Stone Is Gonna Be Famous' => 'Pilot',
		'Zero Hour' => 'Pilot'
	];
}

$maintClass = 'TvEpisodesCovarage';
require( RUN_MAINTENANCE_IF_MAIN );



